### ISSUE TITLE
Consider using visibility private for all fields in a stucture

### ISSUE THREAD

**Issue by DogeThis** [namhkoh/Coronavirus-Bixby-Capsule#1]
https://github.com/namhkoh/Coronavirus-Bixby-Capsule/blob/89590ee6977f6300c0d98b80d20ece52943dc3df/playground.covid19/models/concepts/structures/CountryFieldData.model.bxb#L4

This can save making new concept models

```
property (totalRecovered) {
  description (Question image)
  type (viv.core.Text)
  min (Required) max (One)
  visibility (Private)
}
```

**Comment by namhkoh** [comment]
Wow, the viv.core.* type is a live saver, thank you so much for the suggestion, it is implemented.
